sudo: required
dist: trusty
language: c
compiler:
    - clang
    - gcc
install:
    - if [ "$CC" = "gcc" ]; then export CC="gcc-5"; fi
    - if [ "$CC" = "clang" ]; then export CC="clang-3.7"; fi
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.7 main'
            - sourceline: 'deb-src http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.7 main'
        packages:
            - gcc-5
            - clang-3.7
            - libncursesw5-dev
            - libpulse-dev
            - libasound2-dev
            - libroar-dev
            - libao-dev
            - libjack-dev
            - libsamplerate0-dev
            - libcdio-dev
            - libcdio-cdda-dev
            - libcddb2-dev
            - libcue-dev
            # - libopus-dev
            - libflac-dev
            - libvorbis-dev
            - libmpcdec-dev
            - libwavpack-dev
            - libmad0-dev
            - libavformat-dev
            - libavcodec-dev
            - libfaad-dev
            - libmp4v2-dev
            - libmodplug-dev
            - libmikmod2-dev
script: ./configure && make
